// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waddtxhguitjhdtqydbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZGR0eGhndWl0amhkdHF5ZGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzYxNDEsImV4cCI6MjA2Nzc1MjE0MX0.kufvqmrurAzd18CJJt27tcI0phNP-tjDnEbqo_szGC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});